apiVersion: v1
description: The easy, open source way for everyone in your company to ask questions
  and learn from data.
name: metabase
version: 1.3.3
appVersion: v0.41.5
maintainers:
  - name: pmint93
    email: phamminhthanh69@gmail.com
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg
sources:
  - https://github.com/metabase/metabase
