replicaCount: 1

databases: {}
  # example: "host=127.0.0.1 port=5432 user=pgbouncer"
  # "*": "host=127.0.0.1 port=5432"

users: []
  # - name: bob
  #   password: 3obSecretPwd
  #   options: {} # Override global settings
  #     # pool_mode: transaction
  #     # max_user_connections: 100

connectionLimits:
  max_client_conn: 200
  default_pool_size: 20
  min_pool_size: 15
  reserve_pool_size: 25
  reserve_pool_timeout: 5

logging:
  log_connections: 1
  log_disconnections: 1
  log_pooler_errors: 1
  log_stats: 0
  stats_period: 60
  verbose: 0

settings:
  auth_type: md5
  auth_user: null
  # In order to use auth_query, auth_user must be set
  auth_query: "SELECT usename, passwd FROM pg_shadow WHERE usename=$1"
  pool_mode: session
  admin_users: ""  # Comma-separated list of database users that are allowed to connect and run all commands on the console
  stats_users: ""  # Comma-separated list of database users that are allowed to connect and run read-only queries on the console, eg: SHOW STATS
  client_tls_sslmode: disable
  client_tls_ca_file: null
  client_tls_key_file: null
  client_tls_cert_file: null

extraSettings:
  ignore_startup_parameters: extra_float_digits

existingSecrets: []
# - name: my-cert-secret
#   mountPath: /etc/certs

image:
  repository: hyperized/pgbouncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  # Overrides the image command and args
  command: []
  args:
    - /etc/pgbouncer/pgbouncer.ini

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0

lifecycleHooks: {}
  # preStop:
  #   exec:
  #     command:
  #       - /bin/sh
  #       - -c
  #       - "sleep 10"
  # postStart:
  #   exec:
  #     command:
  #       - /bin/sh
  #       - -c
  #       - "echo 'Container started'"

extraContainerPorts: []
  # - name: pgbouncer
  #   containerPort: 5432
  #   protocol: TCP

service:
  type: ClusterIP
  port: 5432
  extraPorts: []
  # - port: 12345
  #   targetPort: pgbouncer
  #   protocol: TCP
  #   name: pgbouncer

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  enable: false
  name: pgbouncer
  # existingServiceAccountName: ""
  # annotations:
  #   iam.gke.io/gcp-service-account: sa-name@project.iam.gserviceaccount.com

sidecars: []
#  - name: mySidecar
#    image: repo/image:tag
#    imagePullPolicy: IfNotPresent
#    args:
#      - --foo
#      - --bar

terminationGracePeriodSeconds: ""
